services:
  ustatus:
    container_name: ustatus
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./ustatus.json:/ustatus.json
      - ./database.db:/database.db:rw
    environment:
      - USTATUS_DIST=dist
      - USTATUS_PORT=3003
    restart: unless-stopped

