services:
  ustatus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ustatus.json:/ustatus.json
      - ./database.db:/database.db
    environment:
      - USTATUS_DIST=dist
      - USTATUS_PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
